#ifndef DEFS_H
#define DEFS_H

#define RESPONSE_ERROR_LENGHT 4
#define ERROR_CODE_BYTE_SIZE 2

#define INVALID_MESSAGE_CODE 1
#define INCORRECT_MESSAGE_LENGTH 2
#define INVALID_PARAMETER 3
#define INVALID_SINGLE_TOKEN 4
#define ASCII_DECODE_ERROR 5

#define TYPE_BYTE_SIZE 2
#define ID_BYTE_SIZE 12
#define NONCE_BYTE_SIZE 4
#define TOKEN_BYTE_SIZE 64
#define STATUS_BYTE_SIZE 1
#define SAS_NUM_BYTE_SIZE 2
#define SAS_BYTE_SIZE 80

#endif
